src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 55, unique: true)]
    private ?string $username = null;

    #[ORM\Column(length: 55, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(length: 55, nullable: true)]
    private ?string $lastName = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $bio = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $websiteUrl;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $location;

    #[ORM\Column(type: 'date', nullable: true)]
    private $dateOfBirth;

    #[ORM\Column(length: 55)]
    private string $email;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private string $password;

    private ?string $plainPassword;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column]
    #[Gedmo\Timestampable(on: 'create')]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column]
    #[Gedmo\Timestampable(on: 'update')]
    private \DateTimeImmutable $updatedAt;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_name = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Trick::class)]
    private Collection $tricks;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->tricks = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(?string $image_name): static
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): void
    {
        $this->bio = $bio;
    }

    public function getWebsiteUrl()
    {
        return $this->websiteUrl;
    }

    public function setWebsiteUrl($websiteUrl): void
    {
        $this->websiteUrl = $websiteUrl;
    }

    public function getLocation()
    {
        return $this->location;
    }

    public function setLocation($location): void
    {
        $this->location = $location;
    }

    public function getDateOfBirth()
    {
        return $this->dateOfBirth;
    }

    public function setDateOfBirth($dateOfBirth): void
    {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * @return Collection<int, Trick>
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Trick $trick): static
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks->add($trick);
            $trick->setAuthor($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): static
    {
        if ($this->tricks->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getAuthor() === $this) {
                $trick->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\Trick;
use App\Form\CommentFormType;
use App\Form\EditTrickFormType;
use App\Form\TrickFormType;
use App\Repository\CommentRepository;
use App\Repository\TrickRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\String\Slugger\AsciiSlugger;

class TrickController extends AbstractController
{
    #[Route('/comments-partial/{offset}/{trick}', name: 'comments_partial')]
    public function commentsPartial(CommentRepository $commentRepository, TrickRepository $trickRepository, int $offset, Trick $trick): Response
    {
        $trick = $trickRepository->find($trick);
        $paginator = $commentRepository->getCommentPaginator($offset, $trick);

        return $this->render('comment/_comments_partial.html.twig', [
            'trick' => $trick,
            'comments' => $paginator,
        ]);
    }

    #[Route('/tricks-partial/{offset}', name: 'tricks_partial')]
    public function tricksPartial(TrickRepository $trickRepository, int $offset): Response
    {
        $paginator = $trickRepository->getTrickPaginator($offset);

        return $this->render('tricks/partials/_tricks_partial.html.twig', [
            'tricks' => $paginator,
        ]);
    }

    #[Route('/', name: 'app_home')]
    public function index(Request $request, TrickRepository $trickRepository): Response
    {
        $offset = max(0, $request->query->getInt('offset', 0));
        $paginator = $trickRepository->getTrickPaginator($offset);

        return $this->render('main/index.html.twig', [
            'tricks' => $paginator,
            'previous' => $offset - TrickRepository::PAGINATOR_PER_PAGE,
            'next' => $offset + TrickRepository::PAGINATOR_PER_PAGE,
        ]);
    }

    #[Route('/tricks/{slug}', name: 'trick_show')]
    public function show(Request $request, Trick $trick, TrickRepository $trickRepository, CommentRepository $commentRepository): Response
    {
        $trick = $trickRepository->find($trick);
        $media = $trick->getMedia();
        $offset = max(0, $request->query->getInt('offset', 0));
        $paginator = $commentRepository->getCommentPaginator($offset, $trick);

        $form = $this->createForm(CommentFormType::class, null, [
            'trickId' => $trick->getId(),
        ]);

        return $this->render('tricks/single_trick.html.twig', [
            'trick' => $trick,
            'media' => $media,
            'comments' => $paginator,
            'commentForm' => $form->createView(),
            'next' => $offset + $commentRepository::PAGINATOR_PER_PAGE,
        ]);
    }

    #[Route('/trick/new', name: 'trick_new')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function create(Request $request, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(TrickFormType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trick = $form->getData();
            $trick->setAuthor($this->getUser());
            $trick->setSlug((new AsciiSlugger())->slug(strtolower($trick->getName())));

            $this->uploadImages($form, $fileUploader, $trick);

            $entityManager->persist($trick);
            $entityManager->flush();

            $this->addFlash('success', 'Trick created!');

            return $this->redirectToRoute('app_home');
        }

        return $this->render('tricks/new_trick.html.twig', [
            'trickForm' => $form->createView(),
        ]);
    }

    #[Route('/trick/delete/{id}', name: 'trick_delete')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function delete(Trick $trick, EntityManagerInterface $entityManager): Response
    {
        $this->guardAgainstUnauthorizedUser($trick);

        $entityManager->remove($trick);
        $entityManager->flush();

        $this->addFlash('success', 'Trick deleted!');

        return $this->redirectToRoute('app_home');
    }

    #[Route('/trick/edit/{id}', name: 'trick_edit')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function edit(Trick $trick, Request $request, EntityManagerInterface $entityManager, TrickRepository $trickRepository, FileUploader $fileUploader): Response
    {
        $this->guardAgainstUnauthorizedUser($trick);

        $trick = $trickRepository->find($trick);
        $form = $this->createForm(EditTrickFormType::class, $trick);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->uploadVideos($form, $trick);
            $trick = $form->getData();
            $this->uploadImages($form, $fileUploader, $trick);
            $trick->setSlug((new AsciiSlugger())->slug(strtolower($trick->getName())));

            $entityManager->persist($trick);
            $entityManager->flush();

            $this->addFlash('success', 'Trick information modified!');

            return $this->redirectToRoute('trick_show', ['slug' => $trick->getSlug()]);
        }

        return $this->render('tricks/edit-trick-form.html.twig', [
            'trickForm' => $form->createView(),
            'trick' => $trick,
        ]);
    }

    #[Route('/media/edit/{id}', name: 'trick_media_edit')]
    public function edit_media(Trick $trick)
    {
        $this->guardAgainstUnauthorizedUser($trick);

        return $this->render('tricks/edit_media.html.twig', [
            'trick' => $trick,
        ]);
    }

    #[Route('/media/delete/{id}', name: 'trick_media_delete')]
    public function delete_media(Media $media, EntityManagerInterface $entityManager, FileUploader $fileUploader)
    {
        $this->guardAgainstUnauthorizedUser($media->getTrick());

        if ('image' === $media->getType()) {
            $fileUploader->delete($media->getName());
        }

        $entityManager->remove($media);
        $entityManager->flush();

        $this->addFlash('success', 'Media deleted!');

        return $this->redirectToRoute('trick_edit', ['id' => $media->getTrick()->getId()]);
    }

    private function uploadVideos($form, $trick)
    {
        $videos = $form->get('videos')->getData();

        if ($videos) {
            foreach ($videos as $video) {
                $media = new Media();
                $media->setName($video->getName());
                $media->setType('video');
                $trick->addMedium($media);
            }
        }
    }

    private function uploadImages($form, $fileUploader, $trick)
    {
        /** @var UploadedFile[] $profileImageFile */
        $images = $form->get('media')->getData();

        if ($images) {
            foreach ($images as $image) {
                $newFileName = $fileUploader->upload($image);
                $media = new Media();
                $media->setName($newFileName);
                $media->setType('image');
                $trick->addMedium($media);
            }
        }
    }

    private function guardAgainstUnauthorizedUser(Trick $trick): ?RedirectResponse
    {
        if ($trick->getAuthor() !== $this->getUser()) {
            throw new AccessDeniedException('This action is unauthorized!', 403);
        }

        return null;
    }
}

templates/tricks/partials/_card.html.twig
<div class="trick-card transition-all duration-150 flex w-full px-4 py-6 relative">
    {% if is_granted('IS_AUTHENTICATED_FULLY') and trick.author.id is same as app.user.id %}
        <div class="flex absolute top-8 right-4">
            <a href="{{ path('trick_edit', {id: trick.id}) }}">
                <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm p-2.5 text-center inline-flex items-center me-2">
                    <i class="fa-regular fa-pen-to-square"></i>
                </button>
            </a>

            <button data-id="{{ trick.id }}" id="delete-button" data-modal-target="popup-modal" data-modal-toggle="popup-modal" type="button" class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm p-2.5 text-center inline-flex items-center me-2">
                <i class="fa-solid fa-trash"></i>
            </button>

            {{ include('tricks/partials/_modal.html.twig', { id: trick.id, deleteRoute: 'trick_delete' }) }}
        </div>
    {% endif %}

    <div class="flex flex-col w-full items-stretch min-h-full pb-4 mb-6 transition-all duration-150
                    bg-white rounded-lg shadow-lg hover:shadow-2xl">
        <div class="md:flex-shrink-0">
            {% if trick.getMainMedia() %}
                <img src="{{ asset('uploads/images/' ~ trick.getMainMedia().getName()) }}"
                     alt="Blog Cover" class="object-contain w-full rounded-lg rounded-b-none md:h-56"/>
            {% else %}
                <img src='https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png'
                     alt="Blog Cover" class="object-cover w-full rounded-lg rounded-b-none md:h-56"/>
            {% endif %}
        </div>
        <div class="flex flex-wrap items-center flex-1 px-4 py-1 text-center mx-auto">
            <a href="{{ path('trick_show', { slug: trick.slug }) }}" class="hover:underline">
                <h2 class="text-2xl font-bold tracking-normal text-gray-800">
                    {{ trick.name }}
                </h2>
            </a>
        </div>
        <hr class="border-gray-300" />
        <p
                class="w-full my-2 px-4 overflow-hidden text-sm text-justify text-gray-700 line-clamp-3"
        >
            {{ trick.description }}
        </p>
        <hr class="border-gray-300" />
        <section class="px-4 py-2 mt-2">
            <div class="flex items-center justify-between">
                <div class="flex items-center flex-1">
                    {% if trick.author.imageName is not null and trick.author.imageName is defined %}
                        <img
                                src="{{ asset('uploads/images/' ~ trick.author.imageName) }}"
                                class="object-cover h-10 rounded-full"
                                alt="Avatar"
                        />
                    {% else %}
                        <img
                                class="object-cover h-10 rounded-full"
                                src="https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg"
                                alt="Avatar"
                        />
                    {% endif %}
                    <div class="flex flex-col mx-2">
                        <a href="{{ path('user_profile', {id: trick.author.id}) }}" class="font-semibold text-gray-700 hover:underline">
                            {{ trick.author.username }}
                        </a>
                        <span class="text-xs text-gray-600">
                                    {{ trick.createdAt|date('d/m/Y') }}
                            </span>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

templates/tricks/partials/_dropdown.html.twig
{% if is_granted('IS_AUTHENTICATED_FULLY') and trick.author.id is same as app.user.id %}
    <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown" class="btn w-10" type="button">
        <i class="fa-solid fa-ellipsis-vertical"></i>
    </button>
{% endif %}

<div id="dropdown"
     class="ms-6 z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
    <ul class="py-2 text-sm text-gray-700" aria-labelledby="dropdownDefaultButton">
        <li>
            <a href="{{ path('trick_edit', {id: trick.id}) }}"
               class="block px-4 py-2 hover:bg-gray-100">
                Edit
            </a>
        </li>
        <li>
            <button data-modal-target="popup-modal" data-modal-toggle="popup-modal" class="flex w-full text-red-600 px-4 py-2 hover:bg-gray-100" type="button">
                Delete
            </button>
        </li>
    </ul>
</div>

templates/tricks/partials/_modal.html.twig
<div id="popup-modal" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
        <div class="relative bg-white rounded-lg shadow">
            <button type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="popup-modal">
                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="p-4 md:p-5 text-center">
                <svg class="mx-auto mb-4 text-gray-400 w-12 h-12" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                </svg>
                <h3 class="mb-5 text-lg font-normal text-gray-500">Are you sure you want to delete it?</h3>
                <a id="delete-link" href="{{ path(deleteRoute, {id: id|default(':mediaId')}) }}">
                    <button data-modal-hide="popup-modal" type="button" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center me-2">
                        Yes, I'm sure
                    </button>
                </a>
                <button id="delete-button-media" data-modal-hide="popup-modal" type="button" class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10">No, cancel</button>
            </div>
        </div>
    </div>
</div>

templates/tricks/partials/_trick_edit_header.html.twig
{% embed 'shared/_tabs.html.twig' %}
    {% block tabs %}
        {% embed 'shared/_tab.html.twig' with {route: 'trick_edit'} %}
            {% block content %}
                Trick infos
            {% endblock %}
            {% block path %}
                {{ path('trick_edit', {id: trick.id}) }}
            {% endblock %}
        {% endembed %}
        {% embed 'shared/_tab.html.twig' with {route: 'trick_media_edit'} %}
            {% block content %}
                Manage media
            {% endblock %}
            {% block path %}
                {{ path('trick_media_edit', {id: trick.id}) }}
            {% endblock %}
        {% endembed %}
    {% endblock %}
{% endembed %}

templates/tricks/partials/_tricks_partial.html.twig
{% for trick in tricks %}
    {{ include('tricks/partials/_card.html.twig', { trick: trick }) }}
{% endfor %}

templates/tricks/partials/_video.html.twig
{{ form_widget(trickForm.name, {'attr': {'class': 'my-4 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'}}) }}
<button type="button" class="btn-remove h-[40px] text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Remove</button>